[project]
name = "image-factory"
version = "0.1.0"
description = "The official image builder project by Omnivector Solutions"
authors = [
    {name = "matheushent", email = "me@mtosta.dev"},
    {name = "jamesbeedy", email = "james@omnivector.solutions"}
]
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "craft-providers>=2.3.1,<3.0.0",
    "typer>=0.16.0,<1.0.0",
    "click>=8.1.0,<9.0.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.0.282",
    "mypy>=1.4.1",
    "black>=24.3.0",
    "types-pyyaml>=6.0.12.11",
]
website = [
    "aws-cdk-lib>=2.0.0,<3.0.0",
]

[project.scripts]
image-factory = "image_factory.main:app"

[tool.black]
line-length = 110
src = ["image_factory"]

[tool.ruff]
line-length = 110
select = ["E", "W", "F", "C", "N", "D", "I001"]
extend-exclude = ["__pycache__", "*.egg_info", "__init__.py"]
ignore = ["D203", "D212"]

[tool.mypy]
follow_imports = "silent"
ignore_missing_imports = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
