name: "Build image"

on:
  workflow_call:
    inputs:
      jobbergate_version:
        description: "The Jobbergate agent version"
        required: false
        type: string
        default: "4.3.1"

  push:
    branches:
      - main
  pull_request:  

  workflow_dispatch:
    inputs:
      jobbergate_version:
        description: The Jobbergate agent version
        required: false
        type: string
        default: 4.3.1

jobs:
  build-image-in-lxd:
    name: build-image-in-lxd
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install image-factory
        run: |
          poetry env use "3.12"
          poetry install

      - name: Build democluster
        env:
          JG_VERSION: ${{ github.event.inputs.jobbergate_version }}
        run: |
          poetry run image-factory build democluster
